### ISSUE TITLE
断面力図の文字の出力するルールを変更

### ISSUE THREAD

**Issue by sasaco** [structuralengine/FrameWebforJS#137]
大きさが 上位5%の値を印字するルールとしているが、

![image](https://user-images.githubusercontent.com/4043298/147228657-665e5ab5-5c23-45ea-b7d8-38fb962409dd.png)

もうちょっとマシなルールがいい

**Comment by yuluji** [comment]
特徴的な数値（変化点など）を拾い上げて出力するようなアルゴリズムを作成する

**Comment by yuluji** [comment]
①「入力」の「着目点」に入力されている部材の数値を優先して表示する。
②表示が被る部分については“絶対値の大きい方”を優先して表示する。
③数値の最小値を表示する。
④数値の最大値を表示する
⑤同じ材料No を持つ部材の中で 上位〇〇% 以内の数値を表示する。
※①～⑤の数値を合計して全体の50%以内の数値になるように⑤のパーセンテージを調整する

**Comment by yuluji** [comment]
「部材断面力」を開くと画像のように数値が表示される。この数値は部材断面力の大きい順に上位5%が表示される仕組みである。
これを、下記の要件を満たすルールに変更してください。
①「入力」の「着目点」に入力されている部材の数値を優先して表示する。
②表示が被る部分については“絶対値の大きい方”を優先して表示する。
③数値の最小値を表示する。
④数値の最大値を表示する
⑤同じ材料No を持つ部材の中で 上位〇〇% 以内の数値を表示する。
※①～⑤の数値を合計して全体の50%以内の数値になるように⑤のパーセンテージを調整する


![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/c28f72ef-9d00-423d-a650-d9bb538ddfa2)

**Comment by namnguyen0705** [comment]
I couldn't find an image like the one above

**Comment by namnguyen0705** [comment]
I just see
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/93e84b7c-42be-42e5-911f-eab6e007b471)

**Comment by namnguyen0705** [comment]
> 「部材断面力」を開くと画像のように数値が表示される。この数値は部材断面力の大きい順に上位5%が表示される仕組みである。 これを、下記の要件を満たすルールに変更してください。 ①「入力」の「着目点」に入力されている部材の数値を優先して表示する。 ②表示が被る部分については“絶対値の大きい方”を優先して表示する。 ③数値の最小値を表示する。 ④数値の最大値を表示する ⑤同じ材料No を持つ部材の中で 上位〇〇% 以内の数値を表示する。 ※①～⑤の数値を合計して全体の50%以内の数値になるように⑤のパーセンテージを調整する
> 
> ![image](https://user-images.githubusercontent.com/109077766/252532083-c28f72ef-9d00-423d-a650-d9bb538ddfa2.png)

Please use English because I don't understand when used Google Translate from Japanese to Vietnamese

**Comment by yuluji** [comment]
@namnguyen0705 
When you open the "Member Section Force" tab, you will see the values as shown in the image. 
The system displays the top 5% of the values in the order of the member section force.

Please change the rules to meet the following requirements.
(1) Priority is given to displaying the values of members entered in the "Location".
(2) If the values are displayed in the same order, the one with the higher absolute value is given priority.
(3) The minimum value is displayed.
(4) The maximum value is displayed.
(5) Display the numerical value within the upper **xx**% of the parts having the same material No.
_(Adjust the percentage in (5) so that the total of the values in (1) through (5) is within 50% of the total.)_

For the numerical values to be displayed, control is made with src\app\components\three\geometry\three-section-force\three-section-force.service.ts.
