### ISSUE TITLE
節点のフォーカスがずれる

### ISSUE THREAD

**Issue by hisayoshitakeuchi1** [structuralengine/FrameWebforJS#384]

**Comment by yuluji** [comment]
「節点」「部材」「荷重」の入力セルをクリックすると、対応するモデルに対し、水色の円がフォーカスする機能を追加していたが、デザインの変更によってフォーカス位置がずれてしまった。


https://github.com/structuralengine/FrameWebforJS/assets/109077766/1ded3f0f-1ddf-48cc-adad-72e0db4b257e

**Comment by yuluji** [comment]
この機能については、下記を参照の事
https://github.com/structuralengine/FrameWebforJS/issues/327

**Comment by namnguyen0705** [comment]
I noticed that transferring coordinates from the 3D camera is skewed because ThreeJS's screen is not full screen. We have to add the height of the banner vs the header of FrameWebdanJS

![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/1b947764-7c0f-4b9f-ba1b-c99bdf647e38)

Please check it
https://github.com/structuralengine/FrameWebforJS/pull/387
