### ISSUE TITLE
コントロールを多言語化

### ISSUE THREAD

**Issue by yuluji** [structuralengine/FrameWebforJS#492]
現状はコントロールの各項目の名称が英語で固定されているので言語選択によって名称の言語も変更するようにしたいです。

コントロールの表題を下記の言語ファイルをもとに多言語対応してください。
"control"に項目を追加しました。
[cn.json](https://github.com/structuralengine/FrameWebforJS/files/13305342/cn.json)
[en.json](https://github.com/structuralengine/FrameWebforJS/files/13305344/en.json)
[ja.json](https://github.com/structuralengine/FrameWebforJS/files/13305345/ja.json)

![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/bd626a9e-4bfb-450e-9aa7-0201af289c32)
![image](https://github.com/structuralengine/FrameWebforJS/assets/109077766/ec9dd09e-f3a1-47cd-aead-6c5db8a8b328)

**Comment by namnguyen0705** [comment]
can I modify  "dat.gui.module.js" library? because the working library will take the same name as the parameter to draw the control.  
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/8e405f72-bc65-494c-b6e3-a519dad5e768)

initial in ts
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/01ecdff3-4850-421d-8084-8fe06837b832)
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/9272159e-3d1e-4d70-922e-048931041892)

function in library dat.gui.module.js
![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/51991961-be6e-492e-9747-c001157197e9)

![image](https://github.com/structuralengine/FrameWebforJS/assets/103914919/4ec5b501-d434-4361-859a-90f8d81b17de)
